package com.museum.api.common.orm.mapper;

import com.museum.api.common.orm.model.FileResources;
import com.museum.api.common.orm.model.FileResourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int countByExample(FileResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int deleteByExample(FileResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int insert(FileResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int insertSelective(FileResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    List<FileResources> selectByExample(FileResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    FileResources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FileResources record, @Param("example") FileResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FileResources record, @Param("example") FileResourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FileResources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_resources
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FileResources record);
}