package com.museum.api.common.orm.mapper;

import com.museum.api.common.orm.model.FriendshipLink;
import com.museum.api.common.orm.model.FriendshipLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendshipLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int countByExample(FriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int deleteByExample(FriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int insert(FriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int insertSelective(FriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    List<FriendshipLink> selectByExample(FriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    FriendshipLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FriendshipLink record, @Param("example") FriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FriendshipLink record, @Param("example") FriendshipLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendshipLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship_link
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendshipLink record);
}