package com.museum.api.common.orm.mapper;

import com.museum.api.common.orm.model.RelicType;
import com.museum.api.common.orm.model.RelicTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int countByExample(RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int deleteByExample(RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int insert(RelicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int insertSelective(RelicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    List<RelicType> selectByExample(RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    RelicType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelicType record, @Param("example") RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelicType record, @Param("example") RelicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelicType record);
}