package com.museum.api.common.orm.mapper;

import com.museum.api.common.orm.model.RelicImages;
import com.museum.api.common.orm.model.RelicImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelicImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int countByExample(RelicImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int deleteByExample(RelicImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int insert(RelicImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int insertSelective(RelicImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    List<RelicImages> selectByExample(RelicImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    RelicImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelicImages record, @Param("example") RelicImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelicImages record, @Param("example") RelicImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelicImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relic_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelicImages record);
}