package com.museum.api.common.orm.mapper;

import com.museum.api.common.orm.model.ReservationType;
import com.museum.api.common.orm.model.ReservationTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReservationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int countByExample(ReservationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int deleteByExample(ReservationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int insert(ReservationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int insertSelective(ReservationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    List<ReservationType> selectByExample(ReservationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    ReservationType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReservationType record, @Param("example") ReservationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReservationType record, @Param("example") ReservationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReservationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reservation_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReservationType record);
}