package com.museum.api.common.orm.mapper;

import com.museum.api.common.orm.model.UserFuncRel;
import com.museum.api.common.orm.model.UserFuncRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFuncRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int countByExample(UserFuncRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int deleteByExample(UserFuncRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int insert(UserFuncRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int insertSelective(UserFuncRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    List<UserFuncRel> selectByExample(UserFuncRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    UserFuncRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserFuncRel record, @Param("example") UserFuncRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserFuncRel record, @Param("example") UserFuncRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserFuncRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_func_rel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserFuncRel record);
}