package com.museum.api.common.orm.model;

public class Function {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_name
     *
     * @mbggenerated
     */
    private String functionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.id
     *
     * @return the value of function.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.id
     *
     * @param id the value for function.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.menu_id
     *
     * @return the value of function.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.menu_id
     *
     * @param menuId the value for function.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_name
     *
     * @return the value of function.function_name
     *
     * @mbggenerated
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_name
     *
     * @param functionName the value for function.function_name
     *
     * @mbggenerated
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName == null ? null : functionName.trim();
    }
}