package com.museum.api.common.orm.model;

public class RelicType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.relic_type
     *
     * @mbggenerated
     */
    private String relicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_type.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.id
     *
     * @return the value of relic_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.id
     *
     * @param id the value for relic_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.relic_type
     *
     * @return the value of relic_type.relic_type
     *
     * @mbggenerated
     */
    public String getRelicType() {
        return relicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.relic_type
     *
     * @param relicType the value for relic_type.relic_type
     *
     * @mbggenerated
     */
    public void setRelicType(String relicType) {
        this.relicType = relicType == null ? null : relicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.create_by
     *
     * @return the value of relic_type.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.create_by
     *
     * @param createBy the value for relic_type.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.create_time
     *
     * @return the value of relic_type.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.create_time
     *
     * @param createTime the value for relic_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.update_by
     *
     * @return the value of relic_type.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.update_by
     *
     * @param updateBy the value for relic_type.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_type.update_time
     *
     * @return the value of relic_type.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_type.update_time
     *
     * @param updateTime the value for relic_type.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}