package com.museum.api.common.orm.model;

public class RelicImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.relic_id
     *
     * @mbggenerated
     */
    private Integer relicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.file_id
     *
     * @mbggenerated
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic_images.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.id
     *
     * @return the value of relic_images.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.id
     *
     * @param id the value for relic_images.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.relic_id
     *
     * @return the value of relic_images.relic_id
     *
     * @mbggenerated
     */
    public Integer getRelicId() {
        return relicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.relic_id
     *
     * @param relicId the value for relic_images.relic_id
     *
     * @mbggenerated
     */
    public void setRelicId(Integer relicId) {
        this.relicId = relicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.file_id
     *
     * @return the value of relic_images.file_id
     *
     * @mbggenerated
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.file_id
     *
     * @param fileId the value for relic_images.file_id
     *
     * @mbggenerated
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.create_time
     *
     * @return the value of relic_images.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.create_time
     *
     * @param createTime the value for relic_images.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.create_by
     *
     * @return the value of relic_images.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.create_by
     *
     * @param createBy the value for relic_images.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.update_time
     *
     * @return the value of relic_images.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.update_time
     *
     * @param updateTime the value for relic_images.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic_images.update_by
     *
     * @return the value of relic_images.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic_images.update_by
     *
     * @param updateBy the value for relic_images.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
}