package com.museum.api.common.orm.model;

public class Relic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.pic_url
     *
     * @mbggenerated
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.relic_type
     *
     * @mbggenerated
     */
    private Integer relicType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.weight
     *
     * @mbggenerated
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.attrition_rate
     *
     * @mbggenerated
     */
    private String attritionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.application
     *
     * @mbggenerated
     */
    private String application;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.craft
     *
     * @mbggenerated
     */
    private String craft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.material
     *
     * @mbggenerated
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.shape
     *
     * @mbggenerated
     */
    private String shape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.feature
     *
     * @mbggenerated
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.cultural_connotation
     *
     * @mbggenerated
     */
    private String culturalConnotation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.required_tech
     *
     * @mbggenerated
     */
    private String requiredTech;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.age
     *
     * @mbggenerated
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.update_by
     *
     * @mbggenerated
     */
    private Integer updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.protect_value
     *
     * @mbggenerated
     */
    private String protectValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.culture_value
     *
     * @mbggenerated
     */
    private String cultureValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.dynasty
     *
     * @mbggenerated
     */
    private String dynasty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relic.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.id
     *
     * @return the value of relic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.id
     *
     * @param id the value for relic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.name
     *
     * @return the value of relic.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.name
     *
     * @param name the value for relic.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.pic_url
     *
     * @return the value of relic.pic_url
     *
     * @mbggenerated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.pic_url
     *
     * @param picUrl the value for relic.pic_url
     *
     * @mbggenerated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.code
     *
     * @return the value of relic.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.code
     *
     * @param code the value for relic.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.relic_type
     *
     * @return the value of relic.relic_type
     *
     * @mbggenerated
     */
    public Integer getRelicType() {
        return relicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.relic_type
     *
     * @param relicType the value for relic.relic_type
     *
     * @mbggenerated
     */
    public void setRelicType(Integer relicType) {
        this.relicType = relicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.amount
     *
     * @return the value of relic.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.amount
     *
     * @param amount the value for relic.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.level
     *
     * @return the value of relic.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.level
     *
     * @param level the value for relic.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.size
     *
     * @return the value of relic.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.size
     *
     * @param size the value for relic.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.weight
     *
     * @return the value of relic.weight
     *
     * @mbggenerated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.weight
     *
     * @param weight the value for relic.weight
     *
     * @mbggenerated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.attrition_rate
     *
     * @return the value of relic.attrition_rate
     *
     * @mbggenerated
     */
    public String getAttritionRate() {
        return attritionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.attrition_rate
     *
     * @param attritionRate the value for relic.attrition_rate
     *
     * @mbggenerated
     */
    public void setAttritionRate(String attritionRate) {
        this.attritionRate = attritionRate == null ? null : attritionRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.application
     *
     * @return the value of relic.application
     *
     * @mbggenerated
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.application
     *
     * @param application the value for relic.application
     *
     * @mbggenerated
     */
    public void setApplication(String application) {
        this.application = application == null ? null : application.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.craft
     *
     * @return the value of relic.craft
     *
     * @mbggenerated
     */
    public String getCraft() {
        return craft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.craft
     *
     * @param craft the value for relic.craft
     *
     * @mbggenerated
     */
    public void setCraft(String craft) {
        this.craft = craft == null ? null : craft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.material
     *
     * @return the value of relic.material
     *
     * @mbggenerated
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.material
     *
     * @param material the value for relic.material
     *
     * @mbggenerated
     */
    public void setMaterial(String material) {
        this.material = material == null ? null : material.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.shape
     *
     * @return the value of relic.shape
     *
     * @mbggenerated
     */
    public String getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.shape
     *
     * @param shape the value for relic.shape
     *
     * @mbggenerated
     */
    public void setShape(String shape) {
        this.shape = shape == null ? null : shape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.feature
     *
     * @return the value of relic.feature
     *
     * @mbggenerated
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.feature
     *
     * @param feature the value for relic.feature
     *
     * @mbggenerated
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.cultural_connotation
     *
     * @return the value of relic.cultural_connotation
     *
     * @mbggenerated
     */
    public String getCulturalConnotation() {
        return culturalConnotation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.cultural_connotation
     *
     * @param culturalConnotation the value for relic.cultural_connotation
     *
     * @mbggenerated
     */
    public void setCulturalConnotation(String culturalConnotation) {
        this.culturalConnotation = culturalConnotation == null ? null : culturalConnotation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.required_tech
     *
     * @return the value of relic.required_tech
     *
     * @mbggenerated
     */
    public String getRequiredTech() {
        return requiredTech;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.required_tech
     *
     * @param requiredTech the value for relic.required_tech
     *
     * @mbggenerated
     */
    public void setRequiredTech(String requiredTech) {
        this.requiredTech = requiredTech == null ? null : requiredTech.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.area
     *
     * @return the value of relic.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.area
     *
     * @param area the value for relic.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.age
     *
     * @return the value of relic.age
     *
     * @mbggenerated
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.age
     *
     * @param age the value for relic.age
     *
     * @mbggenerated
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.create_by
     *
     * @return the value of relic.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.create_by
     *
     * @param createBy the value for relic.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.create_time
     *
     * @return the value of relic.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.create_time
     *
     * @param createTime the value for relic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.update_by
     *
     * @return the value of relic.update_by
     *
     * @mbggenerated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.update_by
     *
     * @param updateBy the value for relic.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.update_time
     *
     * @return the value of relic.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.update_time
     *
     * @param updateTime the value for relic.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.protect_value
     *
     * @return the value of relic.protect_value
     *
     * @mbggenerated
     */
    public String getProtectValue() {
        return protectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.protect_value
     *
     * @param protectValue the value for relic.protect_value
     *
     * @mbggenerated
     */
    public void setProtectValue(String protectValue) {
        this.protectValue = protectValue == null ? null : protectValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.culture_value
     *
     * @return the value of relic.culture_value
     *
     * @mbggenerated
     */
    public String getCultureValue() {
        return cultureValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.culture_value
     *
     * @param cultureValue the value for relic.culture_value
     *
     * @mbggenerated
     */
    public void setCultureValue(String cultureValue) {
        this.cultureValue = cultureValue == null ? null : cultureValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.dynasty
     *
     * @return the value of relic.dynasty
     *
     * @mbggenerated
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.dynasty
     *
     * @param dynasty the value for relic.dynasty
     *
     * @mbggenerated
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relic.introduction
     *
     * @return the value of relic.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relic.introduction
     *
     * @param introduction the value for relic.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}