package com.museum.api.common.orm.model;

public class UserFuncRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_func_rel.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_func_rel.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_func_rel.func_id
     *
     * @mbggenerated
     */
    private Integer funcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_func_rel.create_time
     *
     * @mbggenerated
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_func_rel.create_by
     *
     * @mbggenerated
     */
    private Integer createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_func_rel.id
     *
     * @return the value of user_func_rel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_func_rel.id
     *
     * @param id the value for user_func_rel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_func_rel.user_id
     *
     * @return the value of user_func_rel.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_func_rel.user_id
     *
     * @param userId the value for user_func_rel.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_func_rel.func_id
     *
     * @return the value of user_func_rel.func_id
     *
     * @mbggenerated
     */
    public Integer getFuncId() {
        return funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_func_rel.func_id
     *
     * @param funcId the value for user_func_rel.func_id
     *
     * @mbggenerated
     */
    public void setFuncId(Integer funcId) {
        this.funcId = funcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_func_rel.create_time
     *
     * @return the value of user_func_rel.create_time
     *
     * @mbggenerated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_func_rel.create_time
     *
     * @param createTime the value for user_func_rel.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_func_rel.create_by
     *
     * @return the value of user_func_rel.create_by
     *
     * @mbggenerated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_func_rel.create_by
     *
     * @param createBy the value for user_func_rel.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
}